const Conversation=require("../models/Conversation");
const Message=require("../models/Message");
const Notification=require("../models/Notification");
const User=require("../models/user");
const mongoose=require("mongoose");
const onlineUsers=new Map();
function setupMessageSocket(io){io.on("connection",socket=>{const userId=socket.userId?.toString();if(!userId)return;const current=onlineUsers.get(userId)||new Set();current.add(socket.id);onlineUsers.set(userId,current);socket.join(`user:${userId}`);io.emit("user:online",{userId});
socket.on("conversation:join",async conversationId=>{try{if(!mongoose.Types.ObjectId.isValid(conversationId))return;const c=await Conversation.findOne({_id:conversationId,participants:userId}).select("_id");if(c)socket.join(`conversation:${conversationId}`);}catch(e){console.error(e.message);}});
socket.on("typing:start",async({conversationId}={})=>{if(await Conversation.exists({_id:conversationId,participants:userId}))socket.to(`conversation:${conversationId}`).emit("typing:start",{userId});});socket.on("typing:stop",async({conversationId}={})=>{if(await Conversation.exists({_id:conversationId,participants:userId}))socket.to(`conversation:${conversationId}`).emit("typing:stop",{userId});});
socket.on("message:send",async({conversationId,text="",replyTo=null,mediaUrl="",mediaType="",profileShareId=null}={})=>{try{const cleanText=typeof text==="string"?text.trim():"";const validMedia=["image","video","profile"].includes(mediaType)&&typeof mediaUrl==="string"&&mediaUrl.trim();if(!cleanText&&!validMedia&&!profileShareId)return;if(cleanText.length>5000)return;const c=await Conversation.findOne({_id:conversationId,participants:userId});if(!c)return;const receiverId=c.participants.find(x=>x.toString()!==userId);if(!receiverId)return;const [target,sender]=await Promise.all([User.findById(receiverId).select("_id fullName isPrivate followers blockedUsers"),User.findById(userId).select("_id fullName blockedUsers")]);if(!target||!sender)return;if(target.blockedUsers?.some(x=>x.toString()===userId)||sender.blockedUsers?.some(x=>x.toString()===receiverId))return socket.emit("message:error",{message:"You cannot message this user."});if(target.isPrivate&&!target.followers.some(x=>x.toString()===userId))return socket.emit("message:error",{message:"This account is private. Follow the user before messaging."});const m=await Message.create({conversationId,senderId:userId,receiverId,text:cleanText,mediaUrl:validMedia&&mediaType!=="profile"?mediaUrl.trim():"",mediaType:profileShareId?"profile":(validMedia?mediaType:""),profileShareId,replyTo});c.lastMessage=m._id;c.lastMessageAt=new Date();await c.save();const payload=await Message.findById(m._id).populate("senderId","fullName profileImageURL").populate("profileShareId","fullName profileImageURL bio isPrivate").lean();await Message.updateOne({_id:m._id},{$set:{status:"delivered"}});io.to(`conversation:${conversationId}`).emit("message:new",{...payload,status:"delivered"});io.to(`user:${receiverId}`).emit("message:new",{...payload,status:"delivered"});const notificationText=cleanText?cleanText.substring(0,120):(profileShareId?"Shared a profile":mediaType==="video"?"Sent a video":"Sent a photo");await Notification.create({recipient:receiverId,type:"message",title:`New message from ${socket.userName||"a user"}`,message:notificationText,actor:userId,messageRef:m._id,conversationId:c._id,isRead:false});io.to(`user:${receiverId}`).emit("notification:message",{conversationId,senderId:userId,messageId:m._id});}catch(e){console.error("message socket:",e.message);socket.emit("message:error",{message:"Unable to send message"});}});
socket.on("message:read",async({conversationId}={})=>{try{if(!mongoose.Types.ObjectId.isValid(conversationId))return;const c=await Conversation.findOne({_id:conversationId,participants:userId}).select("_id participants");if(!c)return;const otherId=c.participants.find(x=>x.toString()!==userId);await Message.updateMany({conversationId,receiverId:userId,isRead:false},{$set:{isRead:true,status:"read"}});await Notification.updateMany({recipient:userId,type:"message",actor:otherId,isRead:false},{$set:{isRead:true}});io.to(`conversation:${conversationId}`).emit("message:read",{conversationId,userId});io.to(`user:${userId}`).emit("message:read",{conversationId,userId});}catch(e){console.error(e.message);}});
socket.on("disconnect",()=>{const set=onlineUsers.get(userId);if(!set)return;set.delete(socket.id);if(!set.size){onlineUsers.delete(userId);io.emit("user:offline",{userId});}});});return onlineUsers;}
module.exports={setupMessageSocket,onlineUsers};