const express=require("express");
const router=express.Router();
const Comment=require("../models/Comment");
const Blog=require("../models/Blog");
const User=require("../models/user");
const {restrictToLoggedInUserOnly}=require("../middlewares/authentication");
const {validateComment}=require("../middlewares/validation");
const NotificationService=require("../services/notificationService");
router.use(restrictToLoggedInUserOnly);

async function canAccessBlog(blog,viewerId){const author=await User.findById(blog.createdBy).select("isPrivate followers").lean();if(!author||!author.isPrivate)return true;return author._id.toString()===viewerId.toString()||author.followers.some(id=>id.toString()===viewerId.toString());}
router.get("/blog/:blogId",async(req,res)=>{try{const blog=await Blog.findById(req.params.blogId);if(!blog)return res.status(404).json({success:false,message:"Blog not found"});if(!(await canAccessBlog(blog,req.user._id)))return res.status(403).json({success:false,message:"Only followers can view comments on this private blog"});const page=parseInt(req.query.page)||1,limit=10,skip=(page-1)*limit;const filter={blog:req.params.blogId,parentComment:null,isDeleted:false};const [comments,total]=await Promise.all([Comment.find(filter).populate("author","fullName profileImageURL").populate({path:"replies",populate:{path:"author",select:"fullName profileImageURL"}}).sort({createdAt:-1}).skip(skip).limit(limit),Comment.countDocuments(filter)]);res.json({success:true,comments,total,pages:Math.ceil(total/limit),currentPage:page});}catch(error){console.error(error);res.status(500).json({success:false,message:"Failed to fetch comments"});}});
router.post("/blog/:blogId",async(req,res)=>{try{const {content,parentCommentId}=req.body;const validation=validateComment(content);if(!validation.isValid)return res.status(400).json({success:false,errors:validation.errors});const blog=await Blog.findById(req.params.blogId);if(!blog)return res.status(404).json({success:false,message:"Blog not found"});if(!(await canAccessBlog(blog,req.user._id)))return res.status(403).json({success:false,message:"Only followers can comment on this private blog"});const comment=await Comment.create({content:content.trim(),blog:blog._id,author:req.user._id,parentComment:parentCommentId||null});if(parentCommentId)await Comment.findByIdAndUpdate(parentCommentId,{$push:{replies:comment._id}});await comment.populate("author","fullName profileImageURL");if(blog.createdBy.toString()!==req.user._id.toString())await NotificationService.createNotification(blog.createdBy,"comment",{title:"New comment",message:`${req.user.fullName} commented on your blog`,blog:blog._id,actor:req.user._id});res.json({success:true,comment});}catch(error){console.error(error);res.status(500).json({success:false,message:"Failed to post comment"});}});
router.put("/:commentId",async(req,res)=>{try{const validation=validateComment(req.body.content);if(!validation.isValid)return res.status(400).json({success:false,errors:validation.errors});const comment=await Comment.findById(req.params.commentId);if(!comment)return res.status(404).json({success:false,message:"Comment not found"});if(comment.author.toString()!==req.user._id.toString())return res.status(403).json({success:false,message:"Not authorized"});comment.content=req.body.content.trim();await comment.save();res.json({success:true,comment});}catch(error){res.status(500).json({success:false,message:"Failed to update comment"});}});
router.delete("/:commentId",async(req,res)=>{try{const comment=await Comment.findById(req.params.commentId);if(!comment)return res.status(404).json({success:false,message:"Comment not found"});if(comment.author.toString()!==req.user._id.toString())return res.status(403).json({success:false,message:"Not authorized"});comment.isDeleted=true;await comment.save();res.json({success:true,message:"Comment deleted"});}catch(error){res.status(500).json({success:false,message:"Failed to delete comment"});}});
router.post("/:commentId/like",async(req,res)=>{try{const comment=await Comment.findById(req.params.commentId);if(!comment)return res.status(404).json({success:false,message:"Comment not found"});const blog=await Blog.findById(comment.blog);if(!blog||!(await canAccessBlog(blog,req.user._id)))return res.status(403).json({success:false,message:"Only followers can like comments on this private blog"});const hasLiked=comment.likes.some(id=>id.toString()===req.user._id.toString());comment.likes=hasLiked?comment.likes.filter(id=>id.toString()!==req.user._id.toString()):[...comment.likes,req.user._id];await comment.save();res.json({success:true,liked:!hasLiked,likeCount:comment.likes.length});}catch(error){res.status(500).json({success:false,message:"Failed to like comment"});}});
module.exports=router;
