const express = require("express");
const router = express.Router();
const User = require("../models/user");
const FollowRequest = require("../models/FollowRequest");
const { restrictToLoggedInUserOnly } = require("../middlewares/authentication");
const NotificationService = require("../services/notificationService");
router.use(restrictToLoggedInUserOnly);
async function notifyRequest(recipient,requester,requestId){try{await NotificationService.createNotification(recipient._id,"follow_request",{title:"Follow request",message:`${requester.fullName} wants to follow you`,actor:requester._id,request:requestId});}catch(e){console.error(e);}}
router.post("/:userId/follow",async(req,res)=>{try{const {userId}=req.params,currentUserId=req.user._id.toString();if(!userId||userId===currentUserId)return res.status(400).json({success:false,message:"Cannot follow yourself"});const [currentUser,targetUser]=await Promise.all([User.findById(currentUserId),User.findById(userId)]);if(!currentUser||!targetUser)return res.status(404).json({success:false,message:"User not found"});if(currentUser.isFollowing(userId)){await Promise.all([User.findByIdAndUpdate(currentUserId,{$pull:{following:userId}}),User.findByIdAndUpdate(userId,{$pull:{followers:currentUserId}}),FollowRequest.deleteMany({requester:currentUserId,recipient:userId,status:"pending"})]);return res.json({success:true,following:false,requested:false,followerCount:Math.max(0,targetUser.followers.length-1),followingCount:Math.max(0,currentUser.following.length-1),message:"Unfollowed successfully"});}if(targetUser.isPrivate){const existing=await FollowRequest.findOne({requester:currentUserId,recipient:userId,status:"pending"});if(existing)return res.json({success:true,following:false,requested:true,followerCount:targetUser.followers.length,followingCount:currentUser.following.length,message:"Follow request already pending"});const request=await FollowRequest.findOneAndUpdate({requester:currentUserId,recipient:userId},{$set:{status:"pending",respondedAt:null}},{upsert:true,new:true,setDefaultsOnInsert:true});await notifyRequest(targetUser,currentUser,request._id);return res.json({success:true,following:false,requested:true,followerCount:targetUser.followers.length,followingCount:currentUser.following.length,message:"Follow request sent"});}await Promise.all([User.findByIdAndUpdate(currentUserId,{$addToSet:{following:userId}}),User.findByIdAndUpdate(userId,{$addToSet:{followers:currentUserId}})]);try{await NotificationService.createNotification(userId,"follow",{title:"New follower",message:`${currentUser.fullName} started following you`,actor:currentUserId});}catch(e){}return res.json({success:true,following:true,requested:false,followerCount:targetUser.followers.length+1,followingCount:currentUser.following.length+1,message:"Followed successfully"});}catch(error){console.error("Follow error:",error);res.status(500).json({success:false,message:error.message||"Failed to follow user"});}});
router.post("/:userId/remove-follower",async(req,res)=>{try{const target=await User.findById(req.params.userId);if(!target)return res.status(404).json({success:false,message:"User not found"});const me=await User.findById(req.user._id).select("followers").lean();const wasFollower=!!me?.followers?.some(id=>id.toString()===target._id.toString());await Promise.all([User.findByIdAndUpdate(req.user._id,{$pull:{followers:target._id}}),User.findByIdAndUpdate(target._id,{$pull:{following:req.user._id}})]);const refreshed=await User.findById(req.user._id).select("followers following").lean();res.json({success:true,followerCount:refreshed?.followers?.length||0,followingCount:refreshed?.following?.length||0,removed:wasFollower,message:`${target.fullName} removed from your followers`});}catch(e){console.error("Remove follower error:",e);res.status(500).json({success:false,message:"Unable to remove follower"});}});
router.post("/requests/:requestId/accept",async(req,res)=>{try{const request=await FollowRequest.findOne({_id:req.params.requestId,recipient:req.user._id,status:"pending"});if(!request)return res.status(404).json({success:false,message:"Follow request not found"});await Promise.all([User.findByIdAndUpdate(request.requester,{$addToSet:{following:request.recipient}}),User.findByIdAndUpdate(request.recipient,{$addToSet:{followers:request.requester}}),FollowRequest.findByIdAndUpdate(request._id,{$set:{status:"accepted",respondedAt:new Date()}})]);const user=await User.findById(req.user._id).select("followers following").lean();res.json({success:true,following:true,followerCount:user?.followers?.length||0,followingCount:user?.following?.length||0,message:"Follow request accepted"});}catch(error){res.status(500).json({success:false,message:"Failed to accept request"});}});
router.post("/requests/:requestId/reject",async(req,res)=>{try{const request=await FollowRequest.findOneAndUpdate({_id:req.params.requestId,recipient:req.user._id,status:"pending"},{$set:{status:"rejected",respondedAt:new Date()}},{new:true});if(!request)return res.status(404).json({success:false,message:"Follow request not found"});res.json({success:true,message:"Follow request rejected"});}catch(error){res.status(500).json({success:false,message:"Failed to reject request"});}});
router.get("/requests/page",(req,res)=>res.render("followRequests",{user:req.user}));
router.get("/requests",async(req,res)=>{try{const requests=await FollowRequest.find({recipient:req.user._id,status:"pending"}).sort({createdAt:-1}).populate("requester","fullName profileImageURL bio").lean();res.json({success:true,requests});}catch(error){res.status(500).json({success:false,message:"Failed to fetch follow requests"});}});
router.get("/:userId/followers",async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page||1,10)||1);const user=await User.findById(req.params.userId).select("followers isPrivate").lean();if(!user)return res.status(404).json({success:false,message:"User not found"});const viewerId=req.user._id.toString();const allowed=user._id.toString()===viewerId||!user.isPrivate||user.followers.some(id=>id.toString()===viewerId);if(!allowed)return res.status(403).json({success:false,message:"Followers list is private",private:true});const total=user.followers.length;const ids=user.followers.slice((page-1)*20,page*20);const followers=ids.length?await User.find({_id:{$in:ids}}).select("fullName profileImageURL bio").lean():[];const order=new Map(ids.map((id,i)=>[id.toString(),i]));followers.sort((a,b)=>order.get(a._id.toString())-order.get(b._id.toString()));res.json({success:true,followers,total,pages:Math.ceil(total/20),page});}catch(error){console.error("Fetch followers error:",error);res.status(500).json({success:false,message:"Failed to fetch followers"});}});
router.get("/:userId/following",async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page||1,10)||1);const user=await User.findById(req.params.userId).select("following followers isPrivate").lean();if(!user)return res.status(404).json({success:false,message:"User not found"});const viewerId=req.user._id.toString();const allowed=user._id.toString()===viewerId||!user.isPrivate||user.followers.some(id=>id.toString()===viewerId);if(!allowed)return res.status(403).json({success:false,message:"Following list is private",private:true});const total=user.following.length;const ids=user.following.slice((page-1)*20,page*20);const following=ids.length?await User.find({_id:{$in:ids}}).select("fullName profileImageURL bio").lean():[];const order=new Map(ids.map((id,i)=>[id.toString(),i]));following.sort((a,b)=>order.get(a._id.toString())-order.get(b._id.toString()));res.json({success:true,following,total,pages:Math.ceil(total/20),page});}catch(error){console.error("Fetch following error:",error);res.status(500).json({success:false,message:"Failed to fetch following"});}});
module.exports=router;
