const express = require("express");
const router = express.Router();
const User = require("../models/user");
const FollowRequest = require("../models/FollowRequest");
const { restrictToLoggedInUserOnly } = require("../middlewares/authentication");
const NotificationService = require("../services/notificationService");
router.use(restrictToLoggedInUserOnly);
async function notifyRequest(recipient,requester,requestId){try{await NotificationService.createNotification(recipient._id,"follow_request",{title:"Follow request",message:`${requester.fullName} wants to follow you`,actor:requester._id,request:requestId});}catch(e){console.error(e);}}
router.post("/:userId/follow",async(req,res)=>{try{const {userId}=req.params,currentUserId=req.user._id.toString();if(!userId||userId===currentUserId)return res.status(400).json({success:false,message:"Cannot follow yourself"});const [currentUser,targetUser]=await Promise.all([User.findById(currentUserId),User.findById(userId)]);if(!currentUser||!targetUser)return res.status(404).json({success:false,message:"User not found"});if(currentUser.isFollowing(userId)){await User.findByIdAndUpdate(currentUserId,{$pull:{following:userId}});await User.findByIdAndUpdate(userId,{$pull:{followers:currentUserId}});await FollowRequest.deleteMany({requester:currentUserId,recipient:userId,status:"pending"});return res.json({success:true,following:false,requested:false,message:"Unfollowed successfully"});}if(targetUser.isPrivate){const existing=await FollowRequest.findOne({requester:currentUserId,recipient:userId,status:"pending"});if(existing)return res.json({success:true,following:false,requested:true,message:"Follow request already pending"});const request=await FollowRequest.findOneAndUpdate({requester:currentUserId,recipient:userId},{$set:{status:"pending",respondedAt:null}},{upsert:true,new:true,setDefaultsOnInsert:true});await notifyRequest(targetUser,currentUser,request._id);return res.json({success:true,following:false,requested:true,message:"Follow request sent"});}await User.findByIdAndUpdate(currentUserId,{$addToSet:{following:userId}});await User.findByIdAndUpdate(userId,{$addToSet:{followers:currentUserId}});try{await NotificationService.createNotification(userId,"follow",{title:"New follower",message:`${currentUser.fullName} started following you`,actor:currentUserId});}catch(e){}return res.json({success:true,following:true,requested:false,message:"Followed successfully"});}catch(error){res.status(500).json({success:false,message:error.message||"Failed to follow user"});}});
router.post("/:userId/remove-follower",async(req,res)=>{try{const target=await User.findById(req.params.userId);if(!target)return res.status(404).json({success:false,message:"User not found"});await User.findByIdAndUpdate(req.user._id,{$pull:{followers:target._id}});await User.findByIdAndUpdate(target._id,{$pull:{following:req.user._id}});res.json({success:true,message:`${target.fullName} removed from your followers`});}catch(e){res.status(500).json({success:false,message:"Unable to remove follower"});}});
router.post("/requests/:requestId/accept",async(req,res)=>{try{const request=await FollowRequest.findOne({_id:req.params.requestId,recipient:req.user._id,status:"pending"});if(!request)return res.status(404).json({success:false,message:"Follow request not found"});await Promise.all([User.findByIdAndUpdate(request.requester,{$addToSet:{following:request.recipient}}),User.findByIdAndUpdate(request.recipient,{$addToSet:{followers:request.requester}}),FollowRequest.findByIdAndUpdate(request._id,{$set:{status:"accepted",respondedAt:new Date()}})]);res.json({success:true,following:true,message:"Follow request accepted"});}catch(error){res.status(500).json({success:false,message:"Failed to accept request"});}});
router.post("/requests/:requestId/reject",async(req,res)=>{try{const request=await FollowRequest.findOneAndUpdate({_id:req.params.requestId,recipient:req.user._id,status:"pending"},{$set:{status:"rejected",respondedAt:new Date()}},{new:true});if(!request)return res.status(404).json({success:false,message:"Follow request not found"});res.json({success:true,message:"Follow request rejected"});}catch(error){res.status(500).json({success:false,message:"Failed to reject request"});}});
router.get("/requests/page",(req,res)=>res.render("followRequests",{user:req.user}));
router.get("/requests",async(req,res)=>{try{const requests=await FollowRequest.find({recipient:req.user._id,status:"pending"}).sort({createdAt:-1}).populate("requester","fullName profileImageURL bio").lean();res.json({success:true,requests});}catch(error){res.status(500).json({success:false,message:"Failed to fetch follow requests"});}});
router.get("/:userId/followers",async(req,res)=>{try{const user=await User.findById(req.params.userId).populate({path:"followers",select:"fullName profileImageURL bio",options:{skip:(parseInt(req.query.page||1)-1)*20,limit:20}});if(!user)return res.status(404).json({success:false,message:"User not found"});const allowed=user._id.toString()===req.user._id.toString()||!user.isPrivate||user.followers.some(id=>id.toString()===req.user._id.toString());if(!allowed)return res.status(403).json({success:false,message:"Followers list is private",private:true});res.json({success:true,followers:user.followers,total:user.followers.length,pages:Math.ceil(user.followers.length/20)});}catch(error){res.status(500).json({success:false,message:"Failed to fetch followers"});}});
router.get("/:userId/following",async(req,res)=>{try{const user=await User.findById(req.params.userId).populate({path:"following",select:"fullName profileImageURL bio",options:{skip:(parseInt(req.query.page||1)-1)*20,limit:20}});if(!user)return res.status(404).json({success:false,message:"User not found"});const allowed=user._id.toString()===req.user._id.toString()||!user.isPrivate||user.followers.some(id=>id.toString()===req.user._id.toString());if(!allowed)return res.status(403).json({success:false,message:"Following list is private",private:true});res.json({success:true,following:user.following,total:user.following.length,pages:Math.ceil(user.following.length/20)});}catch(error){res.status(500).json({success:false,message:"Failed to fetch following"});}});
module.exports=router;