const express=require("express");
const mongoose=require("mongoose");
const Conversation=require("../models/Conversation");
const Message=require("../models/Message");
const User=require("../models/user");
const router=express.Router();
const auth=(req,res,next)=>req.user?next():res.status(401).json({success:false,message:"Authentication required"});
const id=x=>mongoose.Types.ObjectId.isValid(x);
const isFollower=(user,viewerId)=>Array.isArray(user.followers)&&user.followers.some(x=>x.toString()===viewerId.toString());
async function canMessage(senderId,target){return !target.isPrivate||isFollower(target,senderId);}
router.get("/unread/count",auth,async(req,res)=>{try{const count=await Message.countDocuments({receiverId:req.user._id,isRead:false});res.json({success:true,unreadCount:count});}catch(e){res.status(500).json({success:false,message:"Unable to get message count"});}});
router.get("/",auth,async(req,res)=>{try{const list=await Conversation.find({participants:req.user._id}).sort({lastMessageAt:-1,updatedAt:-1}).populate("participants","fullName profileImageURL isPrivate followers").populate("lastMessage","text senderId status isRead createdAt").lean();for(const c of list){c.unreadCount=await Message.countDocuments({conversationId:c._id,receiverId:req.user._id,isRead:false});c.participants=c.participants.map(p=>({_id:p._id,fullName:p.fullName,profileImageURL:p.profileImageURL,isPrivate:p.isPrivate}));}res.json({success:true,conversations:list});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load conversations"});}});
router.post("/conversation",auth,async(req,res)=>{try{const {userId}=req.body;if(!id(userId)||userId.toString()===req.user._id.toString())return res.status(400).json({success:false,message:"Invalid user"});const target=await User.findById(userId).select("_id fullName profileImageURL isPrivate followers");if(!target)return res.status(404).json({success:false,message:"User not found"});if(!(await canMessage(req.user._id,target)))return res.status(403).json({success:false,message:"This account is private. Follow the user before messaging."});let conversation=await Conversation.findOne({participants:{$all:[req.user._id,target._id],$size:2}});if(!conversation)conversation=await Conversation.create({participants:[req.user._id,target._id]});res.json({success:true,conversationId:conversation._id,target:{_id:target._id,fullName:target.fullName,profileImageURL:target.profileImageURL,isPrivate:target.isPrivate}});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to create conversation"});}});
router.get("/:conversationId",auth,async(req,res)=>{try{if(!id(req.params.conversationId))return res.status(400).json({success:false,message:"Invalid conversation"});const c=await Conversation.findOne({_id:req.params.conversationId,participants:req.user._id}).populate("participants","fullName profileImageURL isPrivate");if(!c)return res.status(403).json({success:false,message:"Conversation unavailable"});const messages=await Message.find({conversationId:c._id}).sort({createdAt:1}).populate("senderId","fullName profileImageURL").populate("replyTo","text senderId").lean();await Message.updateMany({conversationId:c._id,receiverId:req.user._id,isRead:false},{$set:{isRead:true,status:"read"}});res.json({success:true,messages,conversation:c});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load messages"});}});
router.post("/:messageId/like",auth,async(req,res)=>{try{if(!id(req.params.messageId))return res.status(400).json({success:false,message:"Invalid message"});const m=await Message.findOne({_id:req.params.messageId,$or:[{senderId:req.user._id},{receiverId:req.user._id}]});if(!m)return res.status(404).json({success:false,message:"Message not found"});const uid=req.user._id.toString();const liked=m.likes.some(x=>x.toString()===uid);if(liked)m.likes.pull(req.user._id);else m.likes.push(req.user._id);await m.save();res.json({success:true,liked:!liked,likes:m.likes.length});}catch(e){res.status(500).json({success:false,message:"Unable to like message"});}});
router.delete("/:messageId",auth,async(req,res)=>{try{if(!id(req.params.messageId))return res.status(400).json({success:false});const m=await Message.findOne({_id:req.params.messageId,senderId:req.user._id});if(!m)return res.status(404).json({success:false,message:"Message not found"});m.text="Message deleted";m.deleted=true;await m.save();res.json({success:true});}catch(e){res.status(500).json({success:false,message:"Unable to delete message"});}});
module.exports=router;