const express=require("express");
const mongoose=require("mongoose");
const multer=require("multer");
const cloudinary=require("cloudinary").v2;
const Conversation=require("../models/Conversation");
const Message=require("../models/Message");
const User=require("../models/user");
const router=express.Router();
const auth=(req,res,next)=>req.user?next():res.status(401).json({success:false,message:"Authentication required"});
const id=x=>mongoose.Types.ObjectId.isValid(x);
const isFollower=(user,viewerId)=>Array.isArray(user.followers)&&user.followers.some(x=>x.toString()===viewerId.toString());
const isBlocked=(user,viewerId)=>Array.isArray(user.blockedUsers)&&user.blockedUsers.some(x=>x.toString()===viewerId.toString());
async function canMessage(senderId,target){return !isBlocked(target,senderId)&&!target.isPrivate||(!isBlocked(target,senderId)&&isFollower(target,senderId));}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:60*1024*1024},fileFilter:(req,file,cb)=>{if(/^image\/(jpeg|jpg|png|gif|webp)$/.test(file.mimetype)||/^video\/(mp4|webm|quicktime|x-msvideo)$/.test(file.mimetype)||/^audio\/(webm|ogg|mpeg|mp4|aac|wav|x-m4a|mp4a-latm)$/.test(file.mimetype))return cb(null,true);cb(new Error("Only images, videos and audio recordings are allowed"));}});
function cloudinaryConfig(){const cloudName=process.env.CLOUD_NAME,apiKey=process.env.API_KEY,apiSecret=process.env.API_SECRET;if(!cloudName||!apiKey||!apiSecret)throw new Error("Image upload service is not configured");cloudinary.config({cloud_name:cloudName,api_key:apiKey,api_secret:apiSecret});}
function uploadToCloudinary(file){cloudinaryConfig();const isAudio=file.mimetype.startsWith("audio/");const resourceType=(file.mimetype.startsWith("video/")||isAudio)?"video":"image";return new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:"blogify/messages",resource_type:resourceType},(err,result)=>{if(err)return reject(err);resolve({url:result.secure_url,type:isAudio?"audio":resourceType});});stream.end(file.buffer);});}
router.get("/unread/count",auth,async(req,res)=>{try{const count=await Message.countDocuments({receiverId:req.user._id,isRead:false});res.json({success:true,unreadCount:count});}catch(e){res.status(500).json({success:false,message:"Unable to get message count"});}});
router.get("/history",auth,async(req,res)=>{try{const userId=req.user._id;const ids=await Message.distinct("conversationId",{$or:[{senderId:userId},{receiverId:userId}],conversationId:{$ne:null}});const result=[];for(const conversationId of ids){if(!id(conversationId))continue;const last=await Message.findOne({conversationId}).sort({createdAt:-1}).select("_id text mediaUrl mediaType profileShareId senderId receiverId status isRead createdAt").lean();if(!last)continue;const participants=await User.find({$or:[{_id:last.senderId},{_id:last.receiverId}]}).select("_id fullName profileImageURL isPrivate blockedUsers").lean();const other=participants.find(p=>String(p._id)!==String(userId));if(!other||isBlocked(other,userId)||isBlocked(participants.find(p=>String(p._id)===String(userId)),other._id))continue;const unreadCount=await Message.countDocuments({conversationId,receiverId:userId,isRead:false});result.push({_id:conversationId,conversationId,participants:participants.map(({blockedUsers,...p})=>p),lastMessage:last,lastMessageAt:last.createdAt,unreadCount});await Conversation.updateOne({_id:conversationId},{$set:{lastMessage:last._id,lastMessageAt:last.createdAt}}).catch(()=>{});}result.sort((a,b)=>new Date(b.lastMessageAt)-new Date(a.lastMessageAt));res.json({success:true,conversations:result});}catch(e){console.error("chat history:",e);res.status(500).json({success:false,message:"Unable to load chat history"});}});
router.get("/",auth,async(req,res)=>{try{const conversations=await Conversation.find({participants:req.user._id}).sort({lastMessageAt:-1,updatedAt:-1}).populate("participants","fullName profileImageURL isPrivate blockedUsers").populate("lastMessage","text mediaUrl mediaType profileShareId senderId status isRead createdAt").lean();const result=[];for(const c of conversations){const other=c.participants.find(p=>String(p._id)!==String(req.user._id));if(!other||isBlocked(other,req.user._id)||isBlocked(c.participants.find(p=>String(p._id)===String(req.user._id)),other._id))continue;let last=c.lastMessage;if(!last)last=await Message.findOne({conversationId:c._id}).sort({createdAt:-1}).lean();if(!last)continue;const unreadCount=await Message.countDocuments({conversationId:c._id,receiverId:req.user._id,isRead:false});result.push({...c,participants:c.participants.map(({blockedUsers,...p})=>p),lastMessage:last,lastMessageAt:last.createdAt,unreadCount});}result.sort((a,b)=>new Date(b.lastMessageAt)-new Date(a.lastMessageAt));res.json({success:true,conversations:result});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load conversations"});}});
router.post("/conversation",auth,async(req,res)=>{try{const {userId}=req.body;if(!id(userId)||userId.toString()===req.user._id.toString())return res.status(400).json({success:false,message:"Invalid user"});const [target,sender]=await Promise.all([User.findById(userId).select("_id fullName profileImageURL isPrivate followers blockedUsers"),User.findById(req.user._id).select("_id blockedUsers")]);if(!target)return res.status(404).json({success:false,message:"User not found"});if(isBlocked(target,req.user._id)||isBlocked(sender,target._id))return res.status(403).json({success:false,message:"You cannot message this user"});if(!(await canMessage(req.user._id,target)))return res.status(403).json({success:false,message:"This account is private. Follow the user before messaging."});let conversation=await Conversation.findOne({participants:{$all:[req.user._id,target._id],$size:2}});if(!conversation)conversation=await Conversation.create({participants:[req.user._id,target._id]});res.json({success:true,conversationId:conversation._id,target:{_id:target._id,fullName:target.fullName,profileImageURL:target.profileImageURL,isPrivate:target.isPrivate}});}catch(e){res.status(500).json({success:false,message:"Unable to create conversation"});}});
router.post("/upload",auth,upload.single("media"),async(req,res)=>{try{if(!req.file)return res.status(400).json({success:false,message:"Select a photo, video or audio recording"});const result=await uploadToCloudinary(req.file);res.json({success:true,mediaUrl:result.url,mediaType:result.type});}catch(e){console.error(e);res.status(400).json({success:false,message:e.message||"Unable to upload media"});}});
router.post("/block/:userId",auth,async(req,res)=>{try{const target=await User.findById(req.params.userId);if(!target||String(target._id)===String(req.user._id))return res.status(404).json({success:false,message:"User not found"});await User.findByIdAndUpdate(req.user._id,{$addToSet:{blockedUsers:target._id},$pull:{following:target._id,followers:target._id}});await User.findByIdAndUpdate(target._id,{$pull:{following:req.user._id,followers:req.user._id}});await Conversation.deleteMany({participants:{$all:[req.user._id,target._id],$size:2}});res.json({success:true,blocked:true,message:`${target.fullName} blocked`});}catch(e){console.error("block user:",e);res.status(500).json({success:false,message:"Unable to block user"});}});
router.delete("/block/:userId",auth,async(req,res)=>{try{if(!id(req.params.userId)||String(req.params.userId)===String(req.user._id))return res.status(400).json({success:false,message:"Invalid user"});await User.findByIdAndUpdate(req.user._id,{$pull:{blockedUsers:req.params.userId}});res.json({success:true,blocked:false});}catch(e){res.status(500).json({success:false,message:"Unable to unblock user"});}});
router.get("/blocked",auth,async(req,res)=>{try{const u=await User.findById(req.user._id).populate("blockedUsers","fullName profileImageURL").lean();res.json({success:true,users:u?.blockedUsers||[]});}catch(e){res.status(500).json({success:false,message:"Unable to load blocked users"});}});
router.post("/share-profile",auth,async(req,res)=>{try{const {recipientId,profileId}=req.body;if(!id(recipientId)||!id(profileId)||String(recipientId)===String(req.user._id))return res.status(400).json({success:false,message:"Invalid recipient"});const [target,profile,sender]=await Promise.all([User.findById(recipientId).select("_id fullName isPrivate followers blockedUsers"),User.findById(profileId).select("_id fullName profileImageURL bio isPrivate"),User.findById(req.user._id).select("_id blockedUsers")]);if(!target||!profile)return res.status(404).json({success:false,message:"User not found"});if(isBlocked(target,req.user._id)||isBlocked(sender,target._id))return res.status(403).json({success:false,message:"You cannot message this user"});if(!(await canMessage(req.user._id,target)))return res.status(403).json({success:false,message:"You cannot message this user"});let c=await Conversation.findOne({participants:{$all:[req.user._id,target._id],$size:2}});if(!c)c=await Conversation.create({participants:[req.user._id,target._id]});const m=await Message.create({conversationId:c._id,senderId:req.user._id,receiverId:target._id,text:`Shared profile: ${profile.fullName}`,mediaType:"profile",profileShareId:profile._id});c.lastMessage=m._id;c.lastMessageAt=new Date();await c.save();res.json({success:true,conversationId:c._id,message:m,profile});}catch(e){console.error("share profile:",e);res.status(500).json({success:false,message:"Unable to share profile"});}});
router.get("/settings",auth,(req,res)=>res.render("message-settings",{title:"Message Settings",user:req.user}));
router.get("/settings/api",auth,async(req,res)=>{try{const user=await User.findById(req.user._id).select("messageSettings").lean();res.json({success:true,messageSettings:user?.messageSettings||{}});}catch(e){res.status(500).json({success:false,message:"Unable to load message settings"});}});
router.patch("/settings/api",auth,async(req,res)=>{try{const allowed=["whoCanMessage","messageRequests","readReceipts","typingIndicator","onlineStatus","messageNotifications","messagePreview","notificationSound","mediaAutoDownload","allowPhotoMessages","allowVideoMessages","messageLikes","groupInvites","hiddenWords","autoDelete"];const updates={};for(const key of allowed)if(Object.prototype.hasOwnProperty.call(req.body,key))updates[`messageSettings.${key}`]=req.body[key];const user=await User.findByIdAndUpdate(req.user._id,{$set:updates},{new:true,runValidators:true}).select("messageSettings").lean();res.json({success:true,messageSettings:user.messageSettings});}catch(e){res.status(400).json({success:false,message:e.message||"Unable to save message settings"});}});
router.delete("/conversation/:conversationId",auth,async(req,res)=>{try{if(!id(req.params.conversationId))return res.status(400).json({success:false,message:"Invalid conversation"});const conversation=await Conversation.findOne({_id:req.params.conversationId,participants:req.user._id}).select("_id participants");if(!conversation)return res.status(404).json({success:false,message:"Conversation not found"});await Message.deleteMany({conversationId:conversation._id});await Conversation.deleteOne({_id:conversation._id});res.json({success:true,message:"Conversation deleted"});}catch(e){console.error("delete conversation:",e);res.status(500).json({success:false,message:"Unable to delete conversation"});}});
router.get("/:conversationId",auth,async(req,res)=>{try{if(!id(req.params.conversationId))return res.status(400).json({success:false,message:"Invalid conversation"});const c=await Conversation.findOne({_id:req.params.conversationId,participants:req.user._id}).populate("participants","fullName profileImageURL isPrivate blockedUsers");if(!c)return res.status(403).json({success:false,message:"Conversation unavailable"});const other=c.participants.find(p=>String(p._id)!==String(req.user._id));const me=c.participants.find(p=>String(p._id)===String(req.user._id));if(!other||isBlocked(other,req.user._id)||isBlocked(me,other._id))return res.status(403).json({success:false,message:"Conversation unavailable"});const messages=await Message.find({conversationId:c._id}).sort({createdAt:1}).populate("senderId","fullName profileImageURL").populate("replyTo","text senderId").populate("profileShareId","fullName profileImageURL bio isPrivate").lean();if(messages.length){const last=messages[messages.length-1];c.lastMessage=last._id;c.lastMessageAt=last.createdAt;await c.save().catch(()=>{});}await Message.updateMany({conversationId:c._id,receiverId:req.user._id,isRead:false},{$set:{isRead:true,status:"read"}});res.json({success:true,messages,conversation:c});}catch(e){console.error("conversation history:",e);res.status(500).json({success:false,message:"Unable to load messages"});}});
router.post("/:messageId/like",auth,async(req,res)=>{try{if(!id(req.params.messageId))return res.status(400).json({success:false,message:"Invalid message"});const m=await Message.findOne({_id:req.params.messageId,$or:[{senderId:req.user._id},{receiverId:req.user._id}]});if(!m)return res.status(404).json({success:false,message:"Message not found"});const uid=req.user._id.toString();const liked=m.likes.some(x=>x.toString()===uid);if(liked)m.likes.pull(req.user._id);else m.likes.push(req.user._id);await m.save();res.json({success:true,liked:!liked,likes:m.likes.length});}catch(e){res.status(500).json({success:false,message:"Unable to like message"});}});
router.delete("/:messageId",auth,async(req,res)=>{try{if(!id(req.params.messageId))return res.status(400).json({success:false,message:"Invalid message"});const m=await Message.findOne({_id:req.params.messageId,senderId:req.user._id});if(!m)return res.status(404).json({success:false,message:"Message not found"});m.text="Message deleted";m.mediaUrl="";m.mediaType="";m.profileShareId=null;m.deleted=true;await m.save();res.json({success:true});}catch(e){res.status(500).json({success:false,message:"Unable to delete message"});}});
module.exports=router;
