const express = require("express");
const router = express.Router();
const Blog = require("../models/Blog");
const User = require("../models/user");
const FollowRequest = require("../models/FollowRequest");
const { restrictToLoggedInUserOnly } = require("../middlewares/authentication");
const cloudinaryUpload = require("../middlewares/CloudinaryUploads");

router.get("/", async (req, res) => { if (!req.user) return res.redirect("/user/signin"); return renderProfile(req, res, req.user._id); });
router.get("/settings", restrictToLoggedInUserOnly, async (req, res) => { try { const user = await User.findById(req.user._id).populate("blockedUsers", "fullName profileImageURL"); if (!user) return res.status(404).send("User not found"); res.render("settings", { user, activeSection: req.query.section || "profile" }); } catch (error) { console.error("Settings Page Error:", error); res.status(500).render("error", { error: error.message }); } });
router.get("/edit", restrictToLoggedInUserOnly, async (req, res) => { try { const user = await User.findById(req.user._id).populate("followers", "fullName profileImageURL").populate("following", "fullName profileImageURL"); res.render("editProfile", { user, success: null, error: null }); } catch (error) { console.error("Edit Profile Page Error:", error); res.status(500).render("error", { error: error.message }); } });
router.get("/:userId", async (req, res) => renderProfile(req, res, req.params.userId));
async function renderProfile(req, res, userId) {
    try {
        // Public profile DTO deliberately excludes email and other account-only fields.
        const user = await User.findById(userId).select("fullName bio website location profileImageURL isPrivate followers following blockedUsers");
        if (!user) return res.status(404).render("error", { error: "User not found" });
        const viewerId = req.user?._id?.toString() || null;
        const isOwnProfile = viewerId === user._id.toString();
        const isFollower = !!(viewerId && user.followers.some(id => id.toString() === viewerId));
        const canViewPrivateContent = isOwnProfile || !user.isPrivate || isFollower;
        let followState = "none";
        if (viewerId && !isOwnProfile) {
            const viewer = await User.findById(viewerId).select("following").lean();
            if (viewer?.following?.some(id => id.toString() === user._id.toString())) followState = "following";
            else if (user.isPrivate && await FollowRequest.exists({ requester: viewerId, recipient: user._id, status: "pending" })) followState = "requested";
        }
        const publishedFilter = { createdBy: user._id, isDeleted: false, status: { $ne: "draft" } };
        const blogCount = await Blog.countDocuments(publishedFilter);
        const blogs = canViewPrivateContent ? await Blog.find(publishedFilter).sort({ createdAt: -1 }).limit(50).lean() : [];
        return res.render("profile", { user, blogs, isOwnProfile, isLoggedIn: !!req.user, isFollower, contentLocked: !canViewPrivateContent, followState, followerCount: user.followers.length, followingCount: user.following.length, blogCount });
    } catch (error) { console.error("Profile Route Error:", error); return res.status(500).render("error", { error: error.message || "Internal Server Error" }); }
}

router.use(restrictToLoggedInUserOnly);
router.put("/update", async (req, res) => { try { const { fullName, bio, website, location } = req.body; const user = await User.findById(req.user._id); if (!user) return res.status(404).json({ success: false, message: "User not found" }); if (typeof fullName === "string" && fullName.trim()) user.fullName = fullName.trim().slice(0, 100); if (typeof bio === "string") user.bio = bio.trim().slice(0, 500); if (typeof website === "string") user.website = website.trim().slice(0, 500); if (typeof location === "string") user.location = location.trim().slice(0, 120); await user.save(); res.json({ success: true, message: "Profile updated successfully", user }); } catch (error) { console.error("Update Profile Error:", error); res.status(500).json({ success: false, message: error.message || "Failed to update profile" }); } });
router.post("/upload-image", (req, res) => { cloudinaryUpload.single("profileImage")(req, res, async (uploadError) => { if (uploadError) { if (uploadError.code === "LIMIT_FILE_SIZE") return res.status(413).json({ success: false, message: "Profile photo must be 10MB or smaller" }); if (uploadError.code === "INVALID_IMAGE_TYPE" || uploadError.code === "LIMIT_UNEXPECTED_FILE") return res.status(400).json({ success: false, message: "Please choose a valid image file" }); return res.status(400).json({ success: false, message: uploadError.message || "Unable to read the selected photo" }); } try { if (!req.file?.buffer?.length) return res.status(400).json({ success: false, message: "Please select a profile photo" }); const uploadResult = await cloudinaryUpload.uploadBuffer(req.file.buffer, { folder: "blogify/profile", resource_type: "image", transformation: [{ width: 800, height: 800, crop: "limit" }] }); const user = await User.findById(req.user._id); if (!user) return res.status(404).json({ success: false, message: "User not found" }); user.profileImageURL = uploadResult.secure_url; await user.save(); res.json({ success: true, message: "Profile photo updated successfully", imageURL: uploadResult.secure_url, user: { id: user._id, profileImageURL: user.profileImageURL } }); } catch (error) { console.error("Profile image upload failed:", error); res.status(500).json({ success: false, message: error.message || "Unable to upload profile photo" }); } }); });
router.patch("/settings/theme", async (req, res) => { try { const theme = String(req.body.theme || "").toLowerCase(); if (!["light", "dark", "system"].includes(theme)) return res.status(400).json({ success: false, message: "Invalid theme" }); const user = await User.findByIdAndUpdate(req.user._id, { theme }, { new: true }); res.json({ success: true, theme: user.theme }); } catch (error) { res.status(500).json({ success: false, message: "Unable to save theme" }); } });
router.patch("/settings/privacy", async (req, res) => { try { const isPrivate = req.body.isPrivate === true || req.body.isPrivate === "true"; const user = await User.findByIdAndUpdate(req.user._id, { isPrivate }, { new: true }); res.json({ success: true, isPrivate: user.isPrivate }); } catch (error) { res.status(500).json({ success: false, message: "Unable to save privacy setting" }); } });
router.patch("/settings/general", async (req, res) => { try { const allowed=["blogSettings","commentSettings","interfaceSettings","notificationSettings"],update={}; for(const group of allowed){if(!req.body[group]||typeof req.body[group]!=="object")continue;for(const [key,value] of Object.entries(req.body[group])){if(group==="blogSettings"&&key==="defaultTags")update[`${group}.${key}`]=Array.isArray(value)?value.map(String).map(v=>v.trim()).filter(Boolean).slice(0,20):[];else if(group==="blogSettings"&&key==="defaultVisibility")update[`${group}.${key}`]=["public","followers"].includes(value)?value:"public";else if(typeof value==="boolean"||typeof value==="string")update[`${group}.${key}`]=value;}} if(!Object.keys(update).length)return res.status(400).json({success:false,message:"No settings supplied"}); const user=await User.findByIdAndUpdate(req.user._id,{$set:update},{new:true});res.json({success:true,settings:{blogSettings:user.blogSettings,commentSettings:user.commentSettings,interfaceSettings:user.interfaceSettings,notificationSettings:user.notificationSettings}}); } catch(error){res.status(500).json({success:false,message:"Unable to save settings"});} });
router.patch("/settings/notifications", async (req,res)=>{try{const allowed=["emailOnComment","emailOnNewFollower","emailOnFollowRequest","emailOnRequestAccepted","emailOnLike","emailOnMention","emailDigest","pushEnabled","pushOnMessage","pushOnComment","pushOnReply","pushOnLike","pushOnFollow","pushOnFollowRequest","pushOnMention","pushOnBlogPost"],update={};for(const key of allowed)if(typeof req.body[key]==="boolean")update[`notificationSettings.${key}`]=req.body[key];if(!Object.keys(update).length)return res.status(400).json({success:false,message:"No notification setting supplied"});const user=await User.findByIdAndUpdate(req.user._id,{$set:update},{new:true});res.json({success:true,notificationSettings:user.notificationSettings});}catch(e){res.status(500).json({success:false,message:"Unable to save notification settings"});}});
async function unblockUserHandler(req,res){try{const user=await User.findById(req.user._id);if(!user)return res.status(404).json({success:false,message:"User not found"});const targetId=String(req.params.userId||"");if(!targetId)return res.status(400).json({success:false,message:"Invalid user"});const before=user.blockedUsers?.length||0;user.blockedUsers=(user.blockedUsers||[]).filter(id=>String(id)!==targetId);await user.save();return res.json({success:true,message:before===(user.blockedUsers?.length||0)?"User was already unblocked":"User unblocked",removed:before!==(user.blockedUsers?.length||0)});}catch(error){console.error("Unblock user error:",error);return res.status(500).json({success:false,message:"Unable to unblock user"});}}
router.patch("/settings/unblock/:userId", unblockUserHandler); router.post("/settings/unblock/:userId", unblockUserHandler);
router.patch("/settings/block/:userId", async (req,res)=>{try{if(String(req.params.userId)===String(req.user._id))return res.status(400).json({success:false,message:"You cannot block yourself"});const user=await User.findById(req.user._id),target=await User.findById(req.params.userId);if(!target)return res.status(404).json({success:false,message:"User not found"});if(!user.blockedUsers.some(id=>id.toString()===target._id.toString())){user.blockedUsers.push(target._id);user.following=user.following.filter(id=>id.toString()!==target._id.toString());user.followers=user.followers.filter(id=>id.toString()!==target._id.toString());await user.save();}res.json({success:true,message:"User blocked"});}catch(error){res.status(500).json({success:false,message:"Unable to block user"});}});
router.post("/change-password", async (req,res)=>{try{const {currentPassword,newPassword}=req.body;if(!currentPassword||!newPassword)return res.status(400).json({success:false,message:"Current and new passwords are required"});if(newPassword.length<8||newPassword.length>256)return res.status(400).json({success:false,message:"New password must be between 8 and 256 characters"});const user=await User.findById(req.user._id);if(!user)return res.status(404).json({success:false,message:"User not found"});if(user.googleId&&!user.password)return res.status(400).json({success:false,message:"This account uses Google Sign-In. Cannot change password."});if(!(await User.verifyPassword(user,currentPassword)))return res.status(401).json({success:false,message:"Current password is incorrect"});user.password=newPassword;await user.save();res.clearCookie("token",{path:"/"});res.json({success:true,message:"Password changed successfully. Please sign in again."});}catch(error){console.error("Change password error:",error);res.status(500).json({success:false,message:"Failed to change password"});}});
router.delete("/delete-account", async (req,res)=>{try{const userId=req.user._id;await Blog.deleteMany({createdBy:userId});await User.findByIdAndDelete(userId);res.clearCookie("token",{path:"/"});res.json({success:true,message:"Account deleted successfully"});}catch(error){res.status(500).json({success:false,message:"Failed to delete account"});}});
module.exports = router;
